config/routes.rb
Rails.application.routes.draw do
  root "pages#main"

  devise_for :users, path: '',
  path_names: {
      sign_in: 'login',
      sign_up: 'register' ,
      sign_out: 'logout'
    }

  resources :contributions, only: [:index, :destroy]
  resources :forms

  scope path: "donate", controller: :forms do
    get '/:slug' => :show
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  has_many :addresses
  has_many :phones
  has_many :emails
  has_many :notes
  has_many :contributions
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :contact
  belongs_to :form
  belongs_to :user
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :contact
end

app/models/form.rb
class Form < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged

  belongs_to :user

  has_many :contributions
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :contact
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forms
  has_many :contributions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_form, only: [:destroy]

  def index
    @contributions = current_user.contributions.all
  end

  def destroy
      if @contributions.destroy && @contributions.present?
          flash[:notice] = "Contribution was removed!"
          redirect_to contributions_path
      else
          flash[:notice] = "Contribution no longer exists! May have been deleted already."
          redirect_to contributions_path
      end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_form, only: [:destroy]

  def index
    @forms = current_user.forms.all
  end

  def new
    @form = Form.new
  end

  def create
     @user = current_user
     @form = @user.forms.build(form_params)
      if @form.save
          flash[:notice] = "Successfully update the form!"
          redirect_to form_path
      else
          render 'new'
      end
  end

  def show
    @form = Form.friendly.find_by(params[:id])
    @contribution = Contribution.new
    @contact = Contact.new
    @phone = Phone.new
    @address = Address.new
    @email = Email.new
  end

  def destroy    
    if @form.destroy && @form.present?
        flash[:notice] = "Form was removed!"
        redirect_to forms_path
    else
        flash[:notice] = "Form no longer exists! May have been deleted already."
        redirect_to forms_path
    end
  end

  private

  def set_form
      @form = Form.find_by(params[:slug])
  end

  def form_params
     params.require(:form).permit(:formName, :formTitle, :formBody, :amountOne, :amountTwo, :amountThree, :amountFour, :amountFive, :slug, :user_id, contributions_attributes: [:amount, :recurring, :token], contacts_attributes: [:firstName, :lastName, :suffix], addresses_attributes: [:one, :two, :city, :zipcode, :mailboxType], phones_attributes: [:numberType, :numberDigits], emails_attributes: [:addressType, :address])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    if user_signed_in?
      @contributions = current_user.contributions.all
      @forms = current_user.forms.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contribution_helper.rb
module ContributionHelper
  def current_user(contribution)
    @contributions = current_user.contributions
  end

  def sum(contribution)
    @contributions.sum :amount
  end

  def count(contribution)
    @contributions.count
  end

  def views(contribution)
    ( @contributions.count )
  end

  def conversion(contribution)
    #Correct math to divide Contribution count from Form views -- Below math is wrong
    (count(@contribution).to_f / views(@contribution).to_f * 100)
  end
end

app/helpers/form_helper.rb
module FormHelper
  def current_user(form)
    @forms = current_user.forms
  end

  def contribution_sum(form)
    form.contributions.sum :amount
  end
end

app/views/contributions/index.html.erb
<%= render partial: "pages/dashboardnav" %>

<!-- Forms Listing -->
<section class="hero is-fullheight-with-navbar is-dashboard-content">
  <div class="container">
    <table class="table contributions-table">
      <thead>
        <tr>
          <th>Contributor Name</th>
          <th>Amount</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
      <% @contributions.each do |contribution| %>
        <tr>
          <th><%= contribution.contact.firstName.capitalize + " " + contribution.contact.lastName.capitalize %>
          <% if contribution.contact.suffix != nil %>
            <%= contribution.contact.suffix %>
          <% end %> <!-- Suffix end --></th>
          <td><%= number_to_currency(contribution.amount, precision: 2, strip_insignificant_zeros: true) %></td>
          <td class="has-text-weight-semibold"><%= link_to "Refund", contributions_path, class:"button is-small is-danger is-rounded" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/forms/components/_box.html.erb
<!-- If LTR statement goes below | Bulma level syntax | Left: Content Right: Wizard -->

<!-- Elsif RTL statement goes below | Bulma level syntax | Left: Wizard Right: Content -->

<!-- Elsif Centered statement goes here followed by End  | Bulma level syntax | Top: Content Bottom: Wizard -->

app/views/forms/components/_content.html.erb
<!-- Headline goes here -->

<!-- Body goes here -->

<!-- Mail check info goes here -->

app/views/forms/components/_wizard.html.erb
<!-- Donation Step by Step wizard goes here -->
<div class="container">
  <div class="wrapper">

    <!-- Steps Header -->
    <ul class="steps">
      <li class="is-active">Step 1</li>
      <li>Step 2</li>
      <li>Step 3</li>
    </ul>

    <!-- Donation Form -->
    <form class="form-wrapper">

      <!-- Step 1 Section | Select Amount Buttons -->
      <fieldset class="section is-active">
        <h3>Select Contribution Amount</h3>
        <div class="row cf">
          <div class="four col">
            <input type="radio" name="r1" id="r1" checked>
            <label for="r1">
              <h4>Amount One</h4>
            </label>
          </div>
          <div class="four col">
            <input type="radio" name="r1" id="r2"><label for="r2">
              <h4>Amount Two</h4>
            </label>
          </div>
          <div class="four col">
            <input type="radio" name="r1" id="r3"><label for="r3">
              <h4>Amount Three</h4>
            </label>
          </div>
        </div>
        <div class="row cf">
          <div class="four col">
            <input type="radio" name="r1" id="r1" checked>
            <label for="r1">
              <h4>Amount Four</h4>
            </label>
          </div>
          <div class="four col">
            <input type="radio" name="r1" id="r2"><label for="r2">
              <h4>Amount Five</h4>
            </label>
          </div>
          <div class="four col">
            <input type="radio" name="r1" id="r3"><label for="r3">
              <h4>Amount Six aka Other</h4>
            </label>
          </div>
        </div>
        <div class="button">Continue</div>
      </fieldset>

      <!-- Step 2 Section | Input Personal Details -->
      <fieldset class="section">
        <h3>Your Details</h3>
        <input type="text" name="name" id="name" placeholder="Name">
        <input type="text" name="email" id="email" placeholder="Email">
        <div class="button">Continue</div>
      </fieldset>


      <!-- Step 3 Section | Input Payment Details -->
      <fieldset class="section">
        <h3>Choose a Password</h3>
        <input type="password" name="password" id="password" placeholder="Password">
        <input type="password" name="password2" id="password2" placeholder="Re-enter Password">
        <input class="submit button" type="submit" value="Submit">
      </fieldset>

      <!-- Confirmation Section | Inform Supporter Contribution Success -->
      <fieldset class="section">
        <h3>Account Created!</h3>
        <p>Your account has now been created.</p>
        <div class="button">Reset Form</div>
      </fieldset>
    </form>
  </div>
</div>

app/views/forms/edit.html.erb
<%= render partial: "pages/dashboardnav" %>

<section class="hero is-fullheight-with-navbar is-dashboard-content">
  <div class="container">
  </div>
</section>

app/views/forms/index.html.erb
<%= render partial: "pages/dashboardnav" %>

<!-- Forms Listing -->
<section class="hero is-fullheight-with-navbar is-dashboard-content">
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th>Form Name</th>
          <th>Created</th>
          <th>Contributions</th>
          <th>Amount</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
      <% @forms.each do |form| %>
        <tr>
          <th><%= form.formName.capitalize %></th>
          <td><%= form.created_at.strftime("%B %d, %Y") %></td>
          <td><%= form.contributions.count %></td>
          <td><%= number_to_currency(contribution_sum(form), precision: 2, strip_insignificant_zeros: true) %></td>
          <td class="has-text-weight-semibold"><%= link_to "Delete", form_path(form), method: :delete, data: {confirm: "Are you sure?"}, class:"button is-small is-danger is-rounded" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/forms/new.html.erb
<%= render partial: "pages/dashboardnav" %>

<section class="hero is-fullheight-with-navbar is-dashboard-content">
  <div class="container">
    <nav class="level">

      <!-- Preview Donation box -->
      <div class="level-left is-donation-box">
      </div>

      <!-- Editor Input Fields -->
      <div class="level-right">
      </div>
    </nav>
  </div>
</section>

app/views/forms/show.html.erb
<!-- Secure Outraise bar goes here -->

<!-- Logo | Header goes here -->

<!-- Box goes here -->
<%= render partial: "forms/components/box" %>

<!-- Disclaimer goes here -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outraise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p-->

    <%= yield %>
  </body>
</html>

app/views/pages/_dashboard.html.erb
<!-- Dashboard -->
<%= render partial: "pages/dashboardnav" %>

<section class="hero is-fullheight-with-navbar is-dashboard-content">
  <div class="container">
    <!-- Dashboard Overview -->
      <nav class="level is-mobile is-dashboard-overview">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading has-text-weight-semibold is-capitalized">views</p>
            <% if count(@contribution) == 0 %>
              <p class="title has-textlink-color">-</p>
            <% else %>
              <p class="title has-textlink-color"><%= number_with_delimiter(views(@contribution)) %></p>
            <% end %>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading has-text-weight-semibold is-capitalized">Contributions</p>
            <% if count(@contribution) == 0 %>
              <p class="title has-textlink-color">-</p>
            <% else %>
              <p class="title has-textlink-color"><%= count(@contribution) %></p>
            <% end %>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading has-text-weight-semibold is-capitalized">Conversion</p>
            <% if count(@contribution) == 0 %>
              <p class="title has-textlink-color">-</p>
            <% else %>
              <p class="title has-textlink-color"><%= number_to_percentage(conversion(@contribution), precision: 1, strip_insignificant_zeros: true) %></p>
            <% end %>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading has-text-weight-semibold is-capitalized">Raised</p>
            <% if count(@contribution) == 0 %>
              <p class="title has-textlink-color">-</p>
            <% else %>
              <p class="title has-textlink-color"><%= number_to_currency(sum(@contribution), precision: 2, strip_insignificant_zeros: true) %></p>
            <% end %>
          </div>
        </div>
      </nav>

      <!-- Forms & Contributions Overview -->
      <nav class="level">
        <!-- Create New Form Button -->
        <div class="level-left is-dashboard-left">
          <%= link_to "Create New Form", new_form_path, class: "button has-background-bablue is-large has-text-weight-semibold is-new-form-button" %>

          <!-- Recent Contributions Listing -->
          <div class="box is-contributions-overview">
            <p class="help is-uppercase has-text-weight-semibold">Recent Contributions
              <% if @contributions.count != 0 %>
                <span><%= link_to "View All", contributions_path, class: "has-text-weight-normal has-textlink-color is-capitalized" %></span>
              <% end %>
            </p>

              <% if @contributions.limit(6).count != 0 %>
                <% @contributions.each do |contribution| %>
                  <p class="help is-contribution has-text-weight-semibold">
                    <%= contribution.contact.firstName.capitalize + " " + contribution.contact.lastName.capitalize %>
                    <% if contribution.contact.suffix != nil %>
                      <%= contribution.contact.suffix %>
                    <% end %> <!-- Suffix end -->
                    <span class="has-textlink-color">
                      <%= number_to_currency(contribution.amount, precision: 2, strip_insignificant_zeros: true) %>
                    </span>
                    </p>
                <% end %> <!-- Contributions Each end -->
              <% else %>
                <div>
                  <p class="help has-text-weight-semibold">
                    You have not received any contributions.
                  </p>
                </div>
              <% end %>
        </div>

      </div>

      <!-- Recent Forms Listing -->
      <div class="level-right is-dashboard-right">
        <div class="box forms-box is-recent-forms">
          <p class="help is-uppercase recent-forms-header">Recent Forms</p>

          <% if @forms.limit(6).count != 0 %>
          <table class="dashboard-table">
            <thead>
              <tr>
                <th class="has-text-weight-semibold">Form Name</th>
                <th class="has-text-weight-semibold">Contributions</th>
                <th class="has-text-weight-semibold">Amount</th>
              </tr>
            </thead>

            <tbody>
            <% @forms.each do |form| %>
              <tr>
                <th class="has-text-weight-normal"><%= form.formName.capitalize %></th>
                <td><%= form.contributions.count %></td>
                <td><%= number_to_currency(contribution_sum(form), precision: 2, strip_insignificant_zeros: true) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <% else %>
            <div>
              <p class="help has-text-weight-semibold">
                You have not created any forms.
              </p>
            </div>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</section>

app/views/pages/_dashboardnav.html.erb
<nav class="navbar has-background-bablue" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Outraise", root_path, class:"navbar-item has-text-weight-bold has-text-white is-lowercase" %>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navhamburger">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navhamburger" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <span class="menulinks has-text-weight-semibold is-lowercase">
            <%= link_to "Donors", contributions_path, class:"has-text-white" %>
            <%= link_to "Forms", forms_path, class:"has-text-white" %>
            <%= link_to "Account", root_path, class:"has-text-white" %>
            <%= link_to("Signout", destroy_user_session_path, method: :delete, class:"has-text-white") %>
          </span>
        </div>
      </div>
    </div>
  </nav>

app/views/pages/_splash.html.erb
<!-- Splash | Pages -->
<section class="hero is-fullheight splash-hero">
  <div class="hero-head">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand title">
          <%= link_to "Outraise", root_path, class:"navbar-item has-text-weight-bold is-lowercase has-text-white" %>

          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navhamburger">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navhamburger" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <span class="menulinks has-text-white">
                <%= link_to "Features", root_path %>
                <%= link_to "Pricing", root_path %>
                <%= link_to "FAQs", root_path %>
                <%= link_to "Login", new_user_session_path %>
              </span>
            </div>
          </div>
        </div>
      </nav>
    </div>

    <div class="hero-body">
      <div class="container">
        <h1 class="title splash-title has-text-weight-bold has-text-white has-text-centered has-decreased-margin has-bottom-padding">
          No more<br>
          Mailed checks.
        </h1>
        <h2 class="subtitle has-text-white has-text-centered has-text-weight-normal">
          Outraise is a powerful, yet simple fundraising platform. Supporters donate using<br> credit card, PayPal or ACH bank transfer then your campaign receive funds instantly.
        </h2>

        <div class="buttons is-centered has-bottom-padding">
          <%= link_to "Get Started for Free", new_user_registration_path, class:"button has-text-weight-semibold is-warning has-text-size-14px is-padded is-uppercase" %>
        </div>
      </div>
    </div>
</section>

app/views/pages/main.html.erb
<% if user_signed_in? %>
  <%= render partial: "pages/dashboard" %>
<% else %>
  <%= render partial: "pages/splash" %>
<% end %>